[package]
name = "rhai-http"
version = "0.1.0"
edition = "2021"
authors = ["ltabis <ltabis.pro@gmail.com>"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
rhai = { version = "1.18", features = ["serde"] }
rhai-dylib = { version = "0.3.0" }
reqwest = { version = "0.12", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }
